export const emails = [
  {
    id: "1",
    email: "alexandra.chen@gmail.com",
    dateJoined: "Jun 23, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products", "Promotions"],
  },
  {
    id: "17",
    email: "jessica.white@gmail.com",
    dateJoined: "Jul 9, 2025",
    status: "active",
    source: "Footer Form",
    preferences: ["New Products", "Promotions"],
  },
  {
    id: "18",
    email: "andrea.lopez@yahoo.com",
    dateJoined: "Jul 10, 2025",
    status: "active",
    source: "Footer Form",
    preferences: ["New Products"],
  },
  {
    id: "2",
    email: "emma.r@outlook.com",
    dateJoined: "Jun 24, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products"],
  },
  {
    id: "3",
    email: "sarahc@yahoo.com",
    dateJoined: "Jun 25, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["Promotions"],
  },
  {
    id: "4",
    email: "mjohnson@gmail.com",
    dateJoined: "Jun 26, 2025",
    status: "unsubscribed",
    source: "Checkout",
    preferences: ["New Products", "Promotions"],
  },
  {
    id: "25",
    email: "christine.lee@outlook.com",
    dateJoined: "Jul 17, 2025",
    status: "active",
    source: "Footer Form",
    preferences: ["New Products", "Promotions"],
  },
  {
    id: "5",
    email: "bella.kim@hotmail.com",
    dateJoined: "Jun 27, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products"],
  },
  {
    id: "6",
    email: "olivia.m@gmail.com",
    dateJoined: "Jun 28, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products", "Promotions"],
  },
  {
    id: "7",
    email: "priya.s@outlook.com",
    dateJoined: "Jun 29, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products"],
  },
  {
    id: "23",
    email: "alice.wong@hotmail.com",
    dateJoined: "Jul 15, 2025",
    status: "active",
    source: "Footer Form",
    preferences: ["New Products", "Promotions"],
  },
  {
    id: "8",
    email: "jwilson@yahoo.com",
    dateJoined: "Jun 30, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["Promotions"],
  },
  {
    id: "9",
    email: "lilyzhang@gmail.com",
    dateJoined: "Jul 1, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products"],
  },
  {
    id: "26",
    email: "helen.nguyen@yahoo.com",
    dateJoined: "Jul 18, 2025",
    status: "active",
    source: "Footer Form",
    preferences: ["New Products"],
  },
  {
    id: "10",
    email: "ava.w@hotmail.com",
    dateJoined: "Jul 2, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products", "Promotions"],
  },
  {
    id: "11",
    email: "nina.p@gmail.com",
    dateJoined: "Jul 3, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["Promotions"],
  },
  {
    id: "12",
    email: "maria.g@outlook.com",
    dateJoined: "Jul 4, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products", "Promotions"],
  },
  {
    id: "22",
    email: "diana.clark@yahoo.com",
    dateJoined: "Jul 14, 2025",
    status: "active",
    source: "Footer Form",
    preferences: ["Promotions"],
  },
  {
    id: "13",
    email: "sofia.m@gmail.com",
    dateJoined: "Jul 5, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products"],
  },
  {
    id: "14",
    email: "rachel.g@hotmail.com",
    dateJoined: "Jul 6, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["Promotions"],
  },
  {
    id: "15",
    email: "david.c@yahoo.com",
    dateJoined: "Jul 7, 2025",
    status: "unsubscribed",
    source: "Checkout",
    preferences: ["New Products"],
  },
  {
    id: "19",
    email: "michelle.tan@hotmail.com",
    dateJoined: "Jul 11, 2025",
    status: "active",
    source: "Footer Form",
    preferences: ["New Products"],
  },
  {
    id: "20",
    email: "karen.thompson@outlook.com",
    dateJoined: "Jul 12, 2025",
    status: "unsubscribed",
    source: "Footer Form",
    preferences: ["Promotions"],
  },
  {
    id: "16",
    email: "maya.s@gmail.com",
    dateJoined: "Jul 8, 2025",
    status: "active",
    source: "Checkout",
    preferences: ["New Products", "Promotions"],
  },
  {
    id: "21",
    email: "rebecca.miller@gmail.com",
    dateJoined: "Jul 13, 2025",
    status: "active",
    source: "Footer Form",
    preferences: ["New Products"],
  },

  {
    id: "24",
    email: "patricia.davis@gmail.com",
    dateJoined: "Jul 16, 2025",
    status: "active",
    source: "Footer Form",
    preferences: ["Promotions"],
  },
];

export const orders = [
  {
    id: "8782",
    product: {
      name: "Silken Touch",
      image: "/1.jpg",
    },
    price: 338,
    Customer: {
      name: "Alexandra Chen",
      email: "alexandra.chen@gmail.com",
    },
    date: "Jun 23, 2025",
    type: "Sale",
    status: "completed",
  },
  {
    id: "8783",
    product: {
      name: "Eternal Youth",
      image: "/2.jpg",
    },
    price: 169,
    Customer: {
      name: "Emma Rodriguez",
      email: "emma.r@outlook.com",
    },
    date: "Jun 24, 2025",
    type: "Sale",
    status: "delivered",
  },
  {
    id: "8784",
    product: {
      name: "Pure Bliss",
      image: "/3.jpg",
    },
    price: 139,
    Customer: {
      name: "Sarah Chen",
      email: "sarahc@yahoo.com",
    },
    date: "Jun 25, 2025",
    type: "Sale",
    status: "shipped",
  },
  {
    id: "8785",
    product: {
      name: "Radiance Revival",
      image: "/4.jpg",
    },
    price: 249,
    Customer: {
      name: "Michael Johnson",
      email: "mjohnson@gmail.com",
    },
    date: "Jun 26, 2025",
    type: "Return",
    status: "completed",
  },
  {
    id: "8786",
    product: {
      name: "Velvet Veil",
      image: "/5.jpg",
    },
    price: 379,
    Customer: {
      name: "Isabella Kim",
      email: "bella.kim@hotmail.com",
    },
    date: "Jun 27, 2025",
    type: "Sale",
    status: "pending",
  },
  {
    id: "8787",
    product: {
      name: "GlowShield SPF7",
      image: "/6.jpg",
    },
    price: 134,
    Customer: {
      name: "Olivia Martinez",
      email: "olivia.m@gmail.com",
    },
    date: "Jun 28, 2025",
    type: "Sale",
    status: "delivered",
  },
  {
    id: "8788",
    product: {
      name: "Eternal Youth",
      image: "/2.jpg",
    },
    price: 169,
    Customer: {
      name: "Priya Sharma",
      email: "priya.s@outlook.com",
    },
    date: "Jun 29, 2025",
    type: "Sale",
    status: "shipped",
  },
  {
    id: "8789",
    product: {
      name: "Silken Touch",
      image: "/1.jpg",
    },
    price: 159,
    Customer: {
      name: "James Wilson",
      email: "jwilson@yahoo.com",
    },
    date: "Jun 30, 2025",
    type: "Return",
    status: "completed",
  },
  {
    id: "8790",
    product: {
      name: "Pure Bliss",
      image: "/3.jpg",
    },
    price: 139,
    Customer: {
      name: "Lily Zhang",
      email: "lilyzhang@gmail.com",
    },
    date: "Jul 1, 2025",
    type: "Sale",
    status: "delivered",
  },
  {
    id: "8791",
    product: {
      name: "Radiance Revival",
      image: "/4.jpg",
    },
    price: 249,
    Customer: {
      name: "Ava Williams",
      email: "ava.w@hotmail.com",
    },
    date: "Jul 2, 2025",
    type: "Sale",
    status: "pending",
  },
  {
    id: "8792",
    product: {
      name: "Velvet Veil",
      image: "/5.jpg",
    },
    price: 379,
    Customer: {
      name: "Nina Patel",
      email: "nina.p@gmail.com",
    },
    date: "Jul 3, 2025",
    type: "Sale",
    status: "shipped",
  },
  {
    id: "8793",
    product: {
      name: "GlowShield SPF7",
      image: "/6.jpg",
    },
    price: 134,
    Customer: {
      name: "Maria Garcia",
      email: "maria.g@outlook.com",
    },
    date: "Jul 4, 2025",
    type: "Sale",
    status: "delivered",
  },
  {
    id: "8794",
    product: {
      name: "Eternal Youth",
      image: "/2.jpg",
    },
    price: 169,
    Customer: {
      name: "Sofia Mendoza",
      email: "sofia.m@gmail.com",
    },
    date: "Jul 5, 2025",
    type: "Sale",
    status: "shipped",
  },
  {
    id: "8795",
    product: {
      name: "Silken Touch",
      image: "/1.jpg",
    },
    price: 159,
    Customer: {
      name: "Rachel Green",
      email: "rachel.g@hotmail.com",
    },
    date: "Jul 6, 2025",
    type: "Sale",
    status: "pending",
  },
  {
    id: "8796",
    product: {
      name: "Pure Bliss",
      image: "/3.jpg",
    },
    price: 139,
    Customer: {
      name: "David Chang",
      email: "david.c@yahoo.com",
    },
    date: "Jul 7, 2025",
    type: "Return",
    status: "completed",
  },
  {
    id: "8797",
    product: {
      name: "Radiance Revival",
      image: "/4.jpg",
    },
    price: 249,
    Customer: {
      name: "Maya Singh",
      email: "maya.s@gmail.com",
    },
    date: "Jul 8, 2025",
    type: "Sale",
    status: "delivered",
  },
  {
    id: "8798",
    product: {
      name: "Velvet Veil",
      image: "/5.jpg",
    },
    price: 379,
    Customer: {
      name: "Victoria Lee",
      email: "victoria.l@outlook.com",
    },
    date: "Jul 9, 2025",
    type: "Sale",
    status: "shipped",
  },
  {
    id: "8799",
    product: {
      name: "GlowShield SPF7",
      image: "/6.jpg",
    },
    price: 134,
    Customer: {
      name: "Elena Romano",
      email: "elena.r@gmail.com",
    },
    date: "Jul 10, 2025",
    type: "Sale",
    status: "completed",
  },
  {
    id: "8800",
    product: {
      name: "Eternal Youth",
      image: "/2.jpg",
    },
    price: 169,
    Customer: {
      name: "Hannah Kim",
      email: "hannah.k@hotmail.com",
    },
    date: "Jul 11, 2025",
    type: "Sale",
    status: "pending",
  },
  {
    id: "8801",
    product: {
      name: "Silken Touch",
      image: "/1.jpg",
    },
    price: 159,
    Customer: {
      name: "Alexandra Wong",
      email: "alex.w@yahoo.com",
    },
    date: "Jul 12, 2025",
    type: "Sale",
    status: "delivered",
  },
  {
    id: "8802",
    product: {
      name: "Pure Bliss",
      image: "/3.jpg",
    },
    price: 139,
    Customer: {
      name: "Zara Ahmed",
      email: "zara.a@gmail.com",
    },
    date: "Jul 13, 2025",
    type: "Sale",
    status: "shipped",
  },
  {
    id: "8803",
    product: {
      name: "Radiance Revival",
      image: "/4.jpg",
    },
    price: 249,
    Customer: {
      name: "Thomas Wilson",
      email: "thomas.w@outlook.com",
    },
    date: "Jul 14, 2025",
    type: "Return",
    status: "completed",
  },
  {
    id: "8804",
    product: {
      name: "Velvet Veil",
      image: "/5.jpg",
    },
    price: 379,
    Customer: {
      name: "Natalie Chen",
      email: "natalie.c@gmail.com",
    },
    date: "Jul 15, 2025",
    type: "Sale",
    status: "pending",
  },
  {
    id: "8805",
    product: {
      name: "GlowShield SPF7",
      image: "/6.jpg",
    },
    price: 134,
    Customer: {
      name: "Julia Santos",
      email: "julia.s@hotmail.com",
    },
    date: "Jul 16, 2025",
    type: "Sale",
    status: "delivered",
  },
  {
    id: "8806",
    product: {
      name: "Eternal Youth",
      image: "/2.jpg",
    },
    price: 169,
    Customer: {
      name: "Sophie Taylor",
      email: "sophie.t@yahoo.com",
    },
    date: "Jul 17, 2025",
    type: "Sale",
    status: "shipped",
  },
  {
    id: "8807",
    product: {
      name: "Silken Touch",
      image: "/1.jpg",
    },
    price: 159,
    Customer: {
      name: "Mia Johnson",
      email: "mia.j@gmail.com",
    },
    date: "Jul 18, 2025",
    type: "Sale",
    status: "completed",
  },
  {
    id: "8808",
    product: {
      name: "Pure Bliss",
      image: "/3.jpg",
    },
    price: 139,
    Customer: {
      name: "Laura Martinez",
      email: "laura.m@outlook.com",
    },
    date: "Jul 19, 2025",
    type: "Sale",
    status: "pending",
  },
  {
    id: "8809",
    product: {
      name: "Radiance Revival",
      image: "/4.jpg",
    },
    price: 249,
    Customer: {
      name: "Isabella Park",
      email: "isabella.p@gmail.com",
    },
    date: "Jul 20, 2025",
    type: "Sale",
    status: "delivered",
  },
  {
    id: "8810",
    product: {
      name: "Velvet Veil",
      image: "/5.jpg",
    },
    price: 379,
    Customer: {
      name: "Emily Watson",
      email: "emily.w@hotmail.com",
    },
    date: "Jul 21, 2025",
    type: "Sale",
    status: "shipped",
  },
  {
    id: "8811",
    product: {
      name: "GlowShield SPF7",
      image: "/6.jpg",
    },
    price: 134,
    Customer: {
      name: "Grace Liu",
      email: "grace.l@yahoo.com",
    },
    date: "Jul 22, 2025",
    type: "Sale",
    status: "completed",
  },
  {
    id: "8812",
    product: {
      name: "Eternal Youth",
      image: "/2.jpg",
    },
    price: 169,
    Customer: {
      name: "Samantha Brown",
      email: "sam.b@gmail.com",
    },
    date: "Jul 23, 2025",
    type: "Sale",
    status: "pending",
  },
];
