name: NVH Luxury E-Commerce Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options: [staging, production]
      force:
        description: 'Force deployment without approval?'
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
    secrets:
      PRODUCTION_API_KEY:
        required: false
  push:
    branches: [main, develop]
    paths-ignore: ['docs/**', 'README.md']
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  init:
    uses: ./.github/workflows/init-version.yml

  setup:
    needs: init
    uses: ./.github/workflows/setup-env.yml
    with:
      release-version: ${{ needs.init.outputs.release-version }}

  lint:
    needs: init
    uses: ./.github/workflows/lint-check.yml

  build:
    needs: [init, setup]
    uses: ./.github/workflows/container-build.yml
    with:
      release-version: ${{ needs.init.outputs.release-version }}

  ci-tests:
    needs: [init, setup, lint]
    uses: ./.github/workflows/ci-tests.yml

  bdd-tests:
    needs: [init, build]
    uses: ./.github/workflows/bdd-tests.yml

  gatekeeper:
    needs: [ci-tests, bdd-tests]
    if: ${{ github.event.inputs.environment == 'production' }}
    uses: ./.github/workflows/gatekeeper.yml

  deploy-staging:
    needs: [ci-tests, bdd-tests]
    if: ${{ github.event.inputs.environment == 'staging' || github.ref == 'refs/heads/develop' }}
    uses: ./.github/workflows/deploy-staging.yml

  deploy-production:
    needs: [gatekeeper, bdd-tests]
    if: ${{ github.event.inputs.environment == 'production' || github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy-production.yml
    with:
      force: ${{ github.event.inputs.force }}

  pr-status:
    if: ${{ github.event_name == 'pull_request' }}
    needs: [ci-tests, bdd-tests]
    uses: ./.github/workflows/pr-quality-gate.yml
