name: Security & Scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Daily at 03:00 UTC

jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: CodeQL Scan
        uses: github/codeql-action/analyze@v2

  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan frontend Docker image
        run: trivy image ghcr.io/${{ github.repository_owner }}/nvh-frontend:latest || true

      - name: Scan backend Docker image
        run: trivy image ghcr.io/${{ github.repository_owner }}/nvh-backend:latest || true

      - name: Scan frontend source code (filesystem scan)
        run: trivy fs ./frontend || true

      - name: Scan backend source code (filesystem scan)
        run: trivy fs ./backend || true
