name: Setup Environment
on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
    outputs:
      node-version:
        description: "Node version from package.json"
        value: ${{ jobs.setup.outputs.node-version }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.set-node.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Node version
        id: set-node
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT